%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

# imu_topic: "/imu_ns/imu/imu_drop"
# imu_topic: "/imu_ns/imu/imu"
imu_topic: "/imu_ns/imu/imu_filter"
image0_topic: "/camera_ns/stereo/left/image_raw"
image1_topic: "/camera_ns/stereo/right/image_raw"
output_path: "/home/vins_fusion_new_ws/src/VINS-Fusion/config/output/"

cam0_calib: "cam_left.yaml"
cam1_calib: "cam_right.yaml"
image_width: 752 #1024
image_height: 480 #768
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.0123167,   0.03419955,  0.99933913,  0.0609592,
           -0.99987632,  0.01019651,  0.01197438,  0.11273441,
           -0.00978026, -0.99936301,  0.03432091, -0.04239318,
           0, 0, 0, 1 ]
#    data: [ 0.00313422,  0.01374308,  0.99990065,  0.03518542,
#            -0.99971866,  0.02355238,  0.00280994,  0.12337551,
#            -0.02351142, -0.99962814,  0.01381303, -0.05746056,
#            0, 0, 0, 1 ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.0195442,   0.01686294,  0.99966678,  0.06218873,
           -0.99980704,  0.00230744,  0.01950802, -0.09820592,
           -0.00197771, -0.99985515,  0.01690478, -0.04415562,
           0, 0, 0, 1 ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 50            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.27 #0.27 #0.2 #0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.20 #0.20 #0.05 #0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.0013 #0.0013 #0.002 #0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.00015 #0.00012 #0.0004 #0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/vins_fusion_new_ws/src/VINS-Fusion/config/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

# mask: 1
# fisheye_mask: "/home/vins_ws/src/VINS-Mono/config/test.jpg"